-include ../Makefile

goroutine: ## run goroutine
	go run goroutine.go

waitgroup: ## run waitgroup
	go run waitgroup.go

mutex: ## run mutex
	go run mutex.go

rwmutex: ## run rwmutex
	go run rwmutex.go
