-include ../Makefile

goroutine: ## run goroutine
	go run goroutine.go

waitgroup: ## run waitgroup
	go run waitgroup.go

mutex: ## run mutex
	go run mutex.go

rwmutex: ## run rwmutex
	go run rwmutex.go

cond: ## run cond
	go run cond.go

broadcast: ## run broadcast
	go run broadcast.go

once: ## run once
	go run once.go

pool: ## run pool
	go run pool.go

channel: ## run channel
	go run channel.go

select: ## run select
	go run select.go
