-include ../Makefile

confinement: ## run confinement
	go run confinement.go

leak: ## run leak
	go run leak.go

or: ## run or
	go run or.go

error: ## run error
	go run error.go

pipeline: ## run pipeline
	go run pipeline.go

fanout: ## run fanout
	go run fanout.go
