-include ../Makefile

error: ## run error
	go run error.go

heartbeat: ## run heartbeat
	go run heartbeat.go

stopbeat: ## run stopbeat
	go run stopbeat.go

heartbeat_test: ## run heartbeat_test
	go test heartbeat_test.go

first: ## run first
	go run first.go
